[local]
localhost

[mongodb]
mongodb.lohithadev.online

[redis]
redis.lohithadev.online

[mysql]
mysql.lohithadev.online

[rabbitmq]
rabbitmq.lohithadev.online

[catalogue]
catalogue.lohithadev.online

[user]
user.lohithadev.online

[cart]
cart.lohithadev.online

[shipping]
shipping.lohithadev.online

[payment]
payment.lohithadev.online

[frontend]
frontend.lohithadev.online

